### ISSUE TITLE
Licensed under GPL-3.0

### ISSUE THREAD

**Issue by tatjana19** [william-ferguson-au/asymmetric-crypto#2]
Hello @william-ferguson-au i see that this project is under GPL-3.0 license.

But in your source code in the license header you write that:

No part of this application may be reproduced, copied, modified or adapted, without the prior written consent of the author, unless otherwise indicated for stand-alone materials.  Contact support@xandar.com.au for copyright requests.

This interfere eachother. So my question is which one is right?

**Comment by william-ferguson-au** [comment]
Woops. It's definitely GPL3. I will scrub those headers from the source.
Looks like they are a remnant from my closed source project from which I excised this library.

Feel free to use as you like.

**Comment by william-ferguson-au** [comment]
I have removed the erroneous copyright headers from the 3 files that needed it.

**Comment by tatjana19** [comment]
Hello @william-ferguson-au, thanks for the fast response. I find your project very interesting. Thank you for sharing :+1:

**Comment by tatjana19** [comment]
Is your project deployed on sonatype, for use as maven dependency?

**Comment by william-ferguson-au** [comment]
No, I haven't set it up.
There hasn't been any interest before :-)
